import time
first_name=input("Enter your first name: ")
surname=input("Enter your surname: ")
age=int(input("How old are you? "))
print("Wow in one year you will be" ,age+1,"Thats very old")
height=float(input("How tall are you in metres? "))
time.sleep(0.5)
print("You are actually very short for a",age,"year old")
time.sleep(0.5)
print("Lets do some math, YAYYYYYYY")
time.sleep(0.5)
number=float(input("Give number please: "))
number_2=float(input("Yo can i get another yo: "))
print("Your sum is ",number + number_2)
time.sleep(0.5)
number_3=float(input("Moar Number: "))
number_4=float(input("more number: "))
print("So here is the minus sum:",number_3 - number_4)
number_5=float(input("Give big number: "))
number_6=float(input("Give smol number: "))
time.sleep(5)
print("Gimme a minute")
time.sleep(4.5)
print("Hold on")
time.sleep(0.5)
print("I divided those:", number_5 / number_6)
print("I also multiplied them:", number_5 * number_6)